Repository thepracticaldev/DEV-Android, pull requests merged in 2020-04, with the labels that each got.

#70 Adds native bridge ability to handle "copy to clipboard" requests from JS
  app/src/main/java/to/dev/dev_android/util/AndroidWebViewBridge.kt
  app/src/main/java/to/dev/dev_android/view/main/view/MainActivity.kt
  buildSrc/src/main/kotlin/Android.kt
  gradle.properties
Labels: PR: reviewed-approved

#60 Add methods to implement native copy-to-clipboard functionality.
  app/src/main/java/to/dev/dev_android/util/AndroidWebViewBridge.kt
Labels: PR: reviewed-approved

#71 Disable backup
  app/src/main/AndroidManifest.xml
  baseui/src/main/AndroidManifest.xml
Labels: PR: unreviewed

#68 Adds Pusher beams and code that enables push notifications handling
  .gitignore
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/to/dev/dev_android/view/main/view/CustomWebViewClient.kt
  app/src/main/java/to/dev/dev_android/view/main/view/MainActivity.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Android.kt
  gradle.properties
Labels: PR: partially-approved

#74 Reverts changes made to AndroidManifest.xml
  app/src/main/AndroidManifest.xml
Labels: PR: reviewed-approved
