Repository thepracticaldev/DEV-Android, pull requests merged in 2020-05, with the labels that each got.

#72 Native Audio Player
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/to/dev/dev_android/media/AudioService.kt
  app/src/main/java/to/dev/dev_android/util/AndroidWebViewBridge.kt
  app/src/main/java/to/dev/dev_android/view/main/view/CustomWebViewClient.kt
  app/src/main/java/to/dev/dev_android/view/main/view/MainActivity.kt
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: PR: reviewed-approved

#75 Some cleanup and enhancements to the Native Audio implementation
  app/build.gradle.kts
  app/src/main/java/to/dev/dev_android/media/AudioService.kt
  app/src/main/java/to/dev/dev_android/media/PodcastPlayerNotificationManager.kt
  app/src/main/java/to/dev/dev_android/util/AndroidWebViewBridge.kt
Labels: PR: partially-approved

#77 Implemented Auto Refresh for WebView
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/to/dev/dev_android/events/NetworkStatusEvent.kt
  app/src/main/java/to/dev/dev_android/util/network/NetworkStatus.kt
  app/src/main/java/to/dev/dev_android/util/network/NetworkUtils.kt
  app/src/main/java/to/dev/dev_android/util/network/NetworkWatcher.kt
  app/src/main/java/to/dev/dev_android/view/main/view/CustomWebViewClient.kt
  app/src/main/java/to/dev/dev_android/view/main/view/MainActivity.kt
  buildSrc/src/main/kotlin/Android.kt
  buildSrc/src/main/kotlin/Libs.kt
  gradle.properties
Labels: PR: reviewed-approved

#80 Removed duplicate .gitignore files and contents merged into one root
  .gitignore
  app/.gitignore
  baseui/.gitignore
  buildSrc/.gitignore
  data/.gitignore
Labels: PR: unreviewed

#83 Includes error url to override for twitter authentication
  app/src/main/java/to/dev/dev_android/view/main/view/CustomWebViewClient.kt
Labels: PR: reviewed-approved
